
[[provider]]
provider = "gitlab"
name = "f5/volterra"
url = "https://gitlab.com"
path = "gitlab-f5"
env_var = "GITLAB_TOKEN"
#skip_forks = true
exclude = [
    "vendor",
    "access-group",
    "lilac-eng",
    "lilac-eng.*",
    "ux",
    "sdc-services",
    "ves-ui-packages",

    "flat.*",
    "sre-prod-model",
    "sre-sb-mec-trial-model",
#    "PKI",
#    "PKI2",
#    "access-log-parser",
#    "aclook",
#    "acmeapi",
#    "acnet",
#    "acorso-test",
#    "acproxyobs",
#    "adns",
#    "alpha",
#    "angular-e2e-testing",
#    "api-security",
#    "apigw-devportal",
#    "apm",
#    "apmaas",
#    "ares",
#    "argo",
#    "ashafix",
#    "asm-insights",
#    "athena",
#    "atributoj",
#    "autentisera",
#    "bfdp",
#    "bgpq3-proxy",
#    "bigcne",
#    "bolt",
#    "bookkeeper",
#    "british",
#    "cacofonix",
#    "cadence-workflow",
#    #"cdn",
#    "client-side-defense",
#    "cloudprotect",
#    "combined-rka-model",
#    "containerized-data-importer",
#    "contrail-dpdk",
#    "coreos-extra-modules",
#    "corero-exporter",
#    "crds-kubevirt",
#    "customer-delivery",
#    "data-plane-api",
#    "datamodel-js",
#    "deploy-kubevirt",
#    "device-id",
#    "devtest",
#    "dnsmasq",
#    #"docker-images",
#    "docker-jenkins",
#    "docker-jenkins-deleteme",
#    "docker-jmeter",
#    "dogmatix",
#    "dpdk-kmods",
#    "dpdk-stable",
#    "dpdk-stable-21.11",
#    "drogon",
#    "dymo",
#    "eks-deployment",
#    "elastalert-yelp",
#    "envoy",
#    "envoy-deps",
#    "eslint-config-ves",
#    "etcd-cpp-apiv3",
#    "exampleuiapp",
#    "export-to-smartsheet",
#    "eywa",
#    "eywaprime",
#    "f-stack",
#    "fireball",
#    "flask-api",
#    "flask-autentisera",
#    "flat-render",
#    "flatrender",
#    "flatrender-apidocs-content",
#    "flatrender-content",
#    "flatrender-core",
#    "flatrender-docs",
#    "flatrender-next",
#    "flatrender-techdocs-content",
#    "fleet-deployment",
#    "form-generator-old",
#    "frr",
#    "ganges",
#    "gatling-simulations",
#    "gatsby",
#    "gatsby-remark-images",
#    "generator-go",
#    "getafix",
#    "git-pack",
#    "gitlab-webhook",
#    "gitops-lilac-f5-prod",
#    "gizmo",
#    "go-control-plane",
#    "go-scim",
#    "go-sfdc",
#    "gocloak",
#    "goflow",
#    "gostrongswanvici",
#    "govanityurls",
#    "grafana",
#    "graveyard",
#    "griffin",
#    "gubernator",
#    "hellas",
#    "identityauthority",
#    "images",
#    "infraprotect-api",
#    "jenkins-pipelines",
#    "josef",
#    "kcdmux",
#    "keepalived",
#    "keypr",
#    "kin-openapi",
#    "kms-demo-app",
#    "ktranslate",
#    "kubevirt",
#    "latency_page",
#    "libevent",
#    "libnvidia-container",
#    "linotp-docker",
#    "lupe",
#    "maglev-hash",
#    "matrix",
#    #"meretrix",
#    "metafrasi",
#    "minerva",
#    "ml-mockserver",
#    "mlresearch",
#    "morpheus",
#    "ncc-proxy",
#    "netapi",
#    "nginx",
#    "nginx-basic-auth",
#    "ngx-datatable",
#    "nvidia-container-runtime",
#    "nvidia-container-toolkit",
#    "nvidia-docker",
#    "nyx",
#    "oas-validator",
#    "obelix",
#    "ocspmule",
#    "olympus",
#    "openmaptiles",
#    "openvpn",
#    "opera",
#    "pacifix",
#    "peering",
#    "pibrac",
#    "pkifactory",
#    "pluto",
#    "pmtud",
#    "porta-buso",
#    "portal",
#    "product",
#    "protekti",
#    "protekti-testing",
#    "rakar",
#    "redoc",
#    "remark42",
#    "request-body-analysis",
#    "rhaegal",
#    "s-test",
#    "saas",
#    "safe-ap",
#    "safed",
#    "sb-ops",
#    "sbdb",
#    "secops",
#    "secops-eks-dev",
#    "secops-keycloak",
#    "secureshare",
#    "security-manager",
#    "security-profiles",
#    "security-reports",
#    "security-research",
#    "sed",
#    "semihalf-work",
#    "service-certs",
#    "service-framework-projects",
#    "shape-recognize",
#    "sia",
#    "siem",
#    "signature_suppression",
#    "snooper_pci-dss",
#    "snupix",
#    "sre-kddi-model",
#    "sre-kdditest-model",
#    "sre-vk8s-model",
#    "stellar",
#    "streak",
#    "strongswan",
#    "test-inputs",
#    "test-npm-registry-project",
#    "test-templating",
#    "test-web-app",
#    "tileserver-gl",
#    "tora",
#    "tpmauthority",
#    "type1-hypervisors-study",
#    "v8",
#    "vaidhix",
#    "vega",
#    "vendor",
#    "ves-lb",
#    "via",
#    "viserion",
#    "vitalstatistix",
#    "vk8s",
#    "vk8s-ui",
#    "volterra-crypto",
#    "volterra-ghost",
#    "volterra-graphs",
#    "volterra-joint-js",
#    "volterra-static-server",
#    "volterra-swagger-parser",
#    "volterra-table",
#    "volterra-ui-components",
#    "volterra-vis",
#    "voltshare-poc",
#    "vpn-checker",
#    "vpn-wrapper",
#    "vulpix",
#    "waap",
#    "waf",
#    "waf-rule-mgr",
#    "walkme-content",
#    "warden",
#    "webroot",
#    "windtunnel",
#    "yaml",
#    "zendesk-apps",
]

# [[provider]]
# provider = "gitlab"
# name = "volterra/security"
# url = "https://gitlab.com"
# path = "gitlab-f5"
# env_var = "GITLAB_TOKEN"

